# -*- coding: utf-8 -*-
"""pycorrector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134Cnru7ylBV-EwipQXu9G9y74FrFaoVS
"""

!pip install https://github.com/kpu/kenlm/archive/master.zip

!pip install pycorrector

!sudo pip install opencc

迫不急待 
怨天由人
別出新裁
祖父去逝
百感焦急
秋水依人
面黃飢瘦
出奇致勝
固步自封
發號司令
素味平生
奈人尋味
興緻勃勃
老生長談

import pycorrector
import opencc

input = '別出新裁'
input = opencc.convert(input, config='t2s.json')

corrected_sent, detail = pycorrector.correct(input)
print(corrected_sent, detail)

corrected_sent = opencc.convert(corrected_sent, config='s2t.json')
print(corrected_sent)